// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Mailwave/mailwave/internal/domain (interfaces: EntitlementProvider)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/Mailwave/mailwave/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockEntitlementProvider is a mock of EntitlementProvider interface.
type MockEntitlementProvider struct {
	ctrl     *gomock.Controller
	recorder *MockEntitlementProviderMockRecorder
}

// MockEntitlementProviderMockRecorder is the mock recorder for MockEntitlementProvider.
type MockEntitlementProviderMockRecorder struct {
	mock *MockEntitlementProvider
}

// NewMockEntitlementProvider creates a new mock instance.
func NewMockEntitlementProvider(ctrl *gomock.Controller) *MockEntitlementProvider {
	mock := &MockEntitlementProvider{ctrl: ctrl}
	mock.recorder = &MockEntitlementProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntitlementProvider) EXPECT() *MockEntitlementProviderMockRecorder {
	return m.recorder
}

// Entitlements mocks base method.
func (m *MockEntitlementProvider) Entitlements() domain.Entitlements {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Entitlements")
	ret0, _ := ret[0].(domain.Entitlements)
	return ret0
}

// Entitlements indicates an expected call of Entitlements.
func (mr *MockEntitlementProviderMockRecorder) Entitlements() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Entitlements", reflect.TypeOf((*MockEntitlementProvider)(nil).Entitlements))
}
