// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Mailwave/mailwave/internal/domain (interfaces: AuditLogService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/Mailwave/mailwave/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockAuditLogService is a mock of AuditLogService interface.
type MockAuditLogService struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogServiceMockRecorder
}

// MockAuditLogServiceMockRecorder is the mock recorder for MockAuditLogService.
type MockAuditLogServiceMockRecorder struct {
	mock *MockAuditLogService
}

// NewMockAuditLogService creates a new mock instance.
func NewMockAuditLogService(ctrl *gomock.Controller) *MockAuditLogService {
	mock := &MockAuditLogService{ctrl: ctrl}
	mock.recorder = &MockAuditLogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogService) EXPECT() *MockAuditLogServiceMockRecorder {
	return m.recorder
}

// Actions mocks base method.
func (m *MockAuditLogService) Actions() []domain.AuditActionDescriptor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Actions")
	ret0, _ := ret[0].([]domain.AuditActionDescriptor)
	return ret0
}

// Actions indicates an expected call of Actions.
func (mr *MockAuditLogServiceMockRecorder) Actions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Actions", reflect.TypeOf((*MockAuditLogService)(nil).Actions))
}

// Export mocks base method.
func (m *MockAuditLogService) Export(arg0 context.Context, arg1 domain.ExportAuditLogsRequest, arg2 io.Writer, arg3 func()) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Export indicates an expected call of Export.
func (mr *MockAuditLogServiceMockRecorder) Export(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockAuditLogService)(nil).Export), arg0, arg1, arg2, arg3)
}

// Get mocks base method.
func (m *MockAuditLogService) Get(arg0 context.Context, arg1, arg2, arg3 string) (*domain.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAuditLogServiceMockRecorder) Get(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAuditLogService)(nil).Get), arg0, arg1, arg2, arg3)
}

// List mocks base method.
func (m *MockAuditLogService) List(arg0 context.Context, arg1 domain.AuditLogFilter) (*domain.ListAuditLogsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*domain.ListAuditLogsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAuditLogServiceMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAuditLogService)(nil).List), arg0, arg1)
}
