// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Mailwave/mailwave/internal/domain (interfaces: AuditLogRecorder)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Mailwave/mailwave/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockAuditLogRecorder is a mock of AuditLogRecorder interface.
type MockAuditLogRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogRecorderMockRecorder
}

// MockAuditLogRecorderMockRecorder is the mock recorder for MockAuditLogRecorder.
type MockAuditLogRecorderMockRecorder struct {
	mock *MockAuditLogRecorder
}

// NewMockAuditLogRecorder creates a new mock instance.
func NewMockAuditLogRecorder(ctrl *gomock.Controller) *MockAuditLogRecorder {
	mock := &MockAuditLogRecorder{ctrl: ctrl}
	mock.recorder = &MockAuditLogRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogRecorder) EXPECT() *MockAuditLogRecorderMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockAuditLogRecorder) Record(arg0 context.Context, arg1 *domain.AuditLog) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", arg0, arg1)
}

// Record indicates an expected call of Record.
func (mr *MockAuditLogRecorderMockRecorder) Record(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockAuditLogRecorder)(nil).Record), arg0, arg1)
}
